# Generated by Django 5.2.10 on 2026-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for the theme (e.g., 'Christmas 2024')", max_length=100)),
                ('theme_type', models.CharField(choices=[('new_years', 'New Years'), ('valentines', 'Valentines Day'), ('st_patricks', "Saint Patrick's Day"), ('mothers_day', "Mother's Day"), ('fathers_day', "Father's Day"), ('fourth_july', '4th of July'), ('rock_n_roll', "Rock'N'Roll Day"), ('thanksgiving', 'Thanksgiving'), ('christmas', 'Christmas'), ('everyday', 'Every Day (Gothic Metal)')], help_text='Type of seasonal theme - determines the animation style', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Enable/disable this theme')),
                ('is_paused', models.BooleanField(default=False, help_text='Temporarily pause animation without deactivating')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority themes take precedence when multiple are active (0 = lowest)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional: Theme activates after this date/time', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: Theme deactivates after this date/time', null=True)),
                ('animation_speed', models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', help_text='Animation playback speed', max_length=20)),
                ('particle_density', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', help_text='Density of animated particles', max_length=20)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for this theme (advanced users only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seasonal Theme',
                'verbose_name_plural': 'Seasonal Themes',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
