# Generated by Django 5.2.10 on 2026-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonaltheme',
            name='theme_type',
            field=models.CharField(choices=[('new_years', 'New Years'), ('valentines', 'Valentines Day'), ('st_patricks', "Saint Patrick's Day"), ('mothers_day', "Mother's Day"), ('fathers_day', "Father's Day"), ('fourth_july', '4th of July'), ('rock_n_roll', "Rock'N'Roll Day"), ('thanksgiving', 'Thanksgiving'), ('christmas', 'Christmas'), ('everyday', 'Every Day (Gothic Metal)'), ('celebration', 'Celebration (Confetti)')], help_text='Type of seasonal theme - determines the animation style', max_length=20, unique=True),
        ),
    ]
