# Generated by Django 5.2.10 on 2026-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_add_celebration_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonaltheme',
            name='show_message_strip',
            field=models.BooleanField(default=False, help_text='Display a scrolling message strip below the vault-hero'),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='strip_color_scheme',
            field=models.CharField(choices=[('theme', 'Match Theme Colors'), ('pink_yellow', 'Pink to Yellow (Default)'), ('custom', 'Custom Gradient')], default='theme', help_text='Color scheme for the message strip', max_length=20),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='strip_custom_gradient',
            field=models.CharField(blank=True, help_text="Custom CSS gradient (e.g., 'linear-gradient(135deg, #ff0000, #00ff00)')", max_length=200),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='strip_messages',
            field=models.TextField(blank=True, help_text="Messages separated by | (e.g., 'HAPPY VALENTINE'S | LOVE FULLY | SPREAD JOY')"),
        ),
        migrations.AddField(
            model_name='seasonaltheme',
            name='strip_scroll_speed',
            field=models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', help_text='Speed of the scrolling text animation', max_length=20),
        ),
    ]
