"""
Django settings for hendoshi_store project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Allowed hosts - include Render hostname and any custom domains
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default='')
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Add custom domain if you have one (e.g., hendoshi.com)
CUSTOM_DOMAIN = config('CUSTOM_DOMAIN', default='')
if CUSTOM_DOMAIN:
    ALLOWED_HOSTS.append(CUSTOM_DOMAIN)
    ALLOWED_HOSTS.append(f'www.{CUSTOM_DOMAIN}')

# CSRF and Security settings for production (Render uses HTTPS proxy)
CSRF_TRUSTED_ORIGINS = []
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')
if CUSTOM_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f'https://{CUSTOM_DOMAIN}')
    CSRF_TRUSTED_ORIGINS.append(f'https://www.{CUSTOM_DOMAIN}')

# Trust the X-Forwarded-Proto header from Render's proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production security settings (only when DEBUG is False)
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'unfold',  # Unfold admin UI (place before django.contrib.admin)
    'unfold.contrib.forms',  # optional: improved form widgets (Select2, etc.)
    'unfold.contrib.inlines',  # optional: improved inline UI
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',  # CSS/JS compression
    'django.contrib.sitemaps',
    'django.contrib.sites',  # Required by allauth
    'ckeditor',  # Rich text editor for admin
    'storages',  # For using S3 in production if needed
    'cloudinary_storage',
    'cloudinary',
    'anymail',  # For Resend email integration
    
    # Hendoshi Apps (must be before allauth for custom template precedence)
    'home',
    'products',
    'cart',
    'checkout',
    'profiles',
    'community',
    'notifications',
    'vault',
    'themes',
    'setup',  # Temporary app for initial data setup

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

# Django Sites Framework (required by allauth)
SITE_ID = 1

# Allauth Authentication Settings
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Configuration
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Allow login with username or email
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'email2*', 'username*', 'password1*', 'password2*']  # Required signup fields
ACCOUNT_USERNAME_MIN_LENGTH = 4
ACCOUNT_LOGOUT_ON_GET = False  # Require POST for logout (security)
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'  # Redirect to homepage after login
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Redirect to homepage after logout

# Email Configuration
# Development: console backend (emails printed to console)
# Production: configure SMTP via environment variables
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
ANYMAIL = {
    "RESEND_API_KEY": config('RESEND_API_KEY', default=''),
}
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='HENDOSHI <noreply@mail.hendoshi.com>')

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'hendoshi_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Add this
                'cart.context_processors.cart_contents',  # Cart context
                'products.context_processors.site_collections_and_types',
                'checkout.context_processors.discount_banner',
                'themes.context_processors.active_seasonal_theme',
                'hendoshi_store.cookie_context_processors.cookie_consent',
                'hendoshi_store.cookie_context_processors.user_preferences',
                'hendoshi_store.cookie_context_processors.recently_viewed_products',
            ],
        },
    },
]

WSGI_APPLICATION = 'hendoshi_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600
    )
}

# Cache configuration
# Uses in-memory cache per process — fast, zero infrastructure required.
# Per-site cache headers are set on public, read-heavy views (product list, vault gallery).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'hendoshi-cache',
        'TIMEOUT': 300,  # 5 minutes default TTL
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Static files are served by WhiteNoise (faster, no S3 costs)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise cache settings
# Files with content hash in name (from CompressedManifestStaticFilesStorage) get 1-year immutable cache
# Files without hash get this TTL as fallback (matched with ?v=X.X versioning in templates)
WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds

# Django Compressor settings for minification
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_CSS_FILTERS = ['compressor.filters.cssmin.CSSMinFilter']
COMPRESS_JS_FILTERS = ['compressor.filters.jsmin.JSMinFilter']

# Media files (User uploads, Product images)
# In development: local storage
# In production: AWS S3
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudinary Configuration for Media Files
import cloudinary
import re

# Support both CLOUDINARY_URL format and individual variables
CLOUDINARY_URL = config('CLOUDINARY_URL', default='')

if CLOUDINARY_URL:
    # Parse CLOUDINARY_URL format: cloudinary://api_key:api_secret@cloud_name
    # Must pass the URL explicitly - cloudinary.config() doesn't auto-read from Python vars
    cloudinary.config(cloudinary_url=CLOUDINARY_URL)
    # Extract cloud_name from the URL for our settings
    match = re.search(r'@([^/]+)$', CLOUDINARY_URL)
    CLOUDINARY_CLOUD_NAME = match.group(1) if match else ''
    print(f"Cloudinary configured from URL. Cloud name: {CLOUDINARY_CLOUD_NAME}")
else:
    # Use individual environment variables
    CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=config('CLOUDINARY_API_KEY', default=''),
        api_secret=config('CLOUDINARY_API_SECRET', default=''),
    )
    print(f"Cloudinary configured from individual vars. Cloud name: {CLOUDINARY_CLOUD_NAME}")

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
}

# Use hybrid Cloudinary + local storage
# Django 4.2+ requires STORAGES dict instead of DEFAULT_FILE_STORAGE
STORAGES = {
    "default": {
        "BACKEND": "products.storage.HybridCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = '/media/'  # Local media URL for existing images

# Stripe configuration
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
STRIPE_CURRENCY = config('STRIPE_CURRENCY', default='usd')
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'