# Generated by Django 5.2.10 on 2026-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='activation_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
