# Generated by Django 5.2.10 on 2026-01-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_discountcode_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE checkout_discountcode (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                code VARCHAR(50) NOT NULL UNIQUE,
                discount_type VARCHAR(20) NOT NULL,
                discount_value DECIMAL(10,2) NOT NULL,
                minimum_order_value DECIMAL(10,2) NOT NULL DEFAULT 0,
                max_uses INTEGER UNSIGNED NOT NULL DEFAULT 0,
                used_count INTEGER UNSIGNED NOT NULL DEFAULT 0,
                is_active BOOLEAN NOT NULL DEFAULT 1,
                expires_at DATETIME NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS checkout_discountcode;"
        ),
    ]
