# Generated by Django 5.2.10 on 2026-01-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_discountcode_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='banner_message',
            field=models.CharField(blank=True, help_text='Custom banner message (leave blank for default)', max_length=200),
        ),
    ]
