# Generated by Django 5.2.10 on 2026-01-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_discountcode_banner_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=0, help_text='Maximum uses per user (0 = unlimited)'),
        ),
    ]
