"""Auto migration: add ShippingRate model

Generated by assistant to add ShippingRate model for frontend admin management.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('checkout', '0010_discountcode_max_uses_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_over', models.DecimalField(blank=True, help_text='If set, shipping is free when order subtotal >= this value', max_digits=10, null=True, decimal_places=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
