# Generated by Django 5.2.10 on 2026-01-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_shippingrate_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='banner_button',
            field=models.CharField(choices=[('none', 'No Button'), ('shop_now', 'Shop Now'), ('sale', 'Sale')], default='none', help_text='Button to display with the discount code', max_length=20),
        ),
    ]
