# Generated by Django 5.2.10 on 2026-02-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_alter_orderitem_color_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('usps', 'USPS'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
