# Generated by Django 5.2.10 on 2026-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True for customer welcome codes (auto-generated). These are excluded from the discount banner.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('anpost', 'An Post'), ('dpd', 'DPD'), ('usps', 'USPS'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
