# Generated by Django 5.2.10 on 2026-01-20 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_product_sale_end_product_sale_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload your photo wearing HENDOSHI gear', upload_to='vault/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption (max 200 characters)', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.PositiveIntegerField(default=0, help_text='Number of likes (future feature)')),
                ('tagged_products', models.ManyToManyField(blank=True, help_text="Tag the HENDOSHI products you're wearing", related_name='vault_photos', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Photo',
                'verbose_name_plural': 'Vault Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
