# Generated by Django 5.2.10 on 2026-01-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultphoto',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption (max 800 characters)', max_length=800),
        ),
    ]
