# Generated by Django 5.2.10 on 2026-01-20 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_vaultphoto_caption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultphoto',
            name='likes',
        ),
        migrations.AddField(
            model_name='vaultphoto',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_vault_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
