# Generated by Django 5.2.10 on 2026-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_remove_vaultphoto_likes_vaultphoto_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultphoto',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=10),
        ),
    ]
