# Generated by Django 5.2.10 on 2026-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_vaultphoto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultphoto',
            name='feature_score',
            field=models.IntegerField(default=0, help_text='Score for determining feature worthiness (likes + engagement)'),
        ),
        migrations.AddField(
            model_name='vaultphoto',
            name='featured_date',
            field=models.DateTimeField(blank=True, help_text='When this photo was first featured', null=True),
        ),
        migrations.AddField(
            model_name='vaultphoto',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='When the feature period ends', null=True),
        ),
        migrations.AddField(
            model_name='vaultphoto',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Is this photo currently featured?'),
        ),
    ]
