# Generated by Django 5.2.10 on 2026-01-20 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_vaultphoto_feature_score_vaultphoto_featured_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultphoto',
            name='downvotes',
            field=models.ManyToManyField(blank=True, help_text='Users who downvoted this photo', related_name='downvoted_vault_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaultphoto',
            name='upvotes',
            field=models.ManyToManyField(blank=True, help_text='Users who upvoted this photo', related_name='upvoted_vault_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaultphoto',
            name='vote_score',
            field=models.IntegerField(default=0, help_text='Net vote score (upvotes - downvotes)'),
        ),
    ]
