# Generated by Django 5.2.10 on 2026-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='vault_photo_notifications',
            field=models.BooleanField(default=True, help_text='Receive emails when your vault photo submissions are reviewed'),
        ),
    ]
