# Generated by Django 5.2.10 on 2026-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference_vault_photo_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='vault_featured_notifications',
            field=models.BooleanField(default=True, help_text='Receive emails when your vault photos are featured'),
        ),
    ]
