# Generated by Django 5.2.10 on 2026-01-27 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('notifications', '0004_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='cart_abandonment_notifications',
            field=models.BooleanField(default=True, help_text='Receive reminders when you leave items in your cart'),
        ),
        migrations.CreateModel(
            name='AbandonedCartNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('recovered', 'Cart Recovered')], default='pending', max_length=10)),
                ('reminder_number', models.PositiveSmallIntegerField(default=1, help_text='1st, 2nd, or 3rd reminder')),
                ('cart_last_activity', models.DateTimeField(help_text='When the cart was last modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandonment_notifications', to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_abandonment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abandoned Cart Notification',
                'verbose_name_plural': 'Abandoned Cart Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_7d4b09_idx'), models.Index(fields=['user', 'cart', 'reminder_number'], name='notificatio_user_id_fc26bd_idx')],
            },
        ),
    ]
