# Generated by Django 4.2.7 on 2026-01-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.SlugField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/')),
            ],
            options={
                'verbose_name_plural': 'Collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.SlugField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('tshirt', 'T-Shirt'), ('hoodie', 'Hoodie'), ('sticker', 'Sticker'), ('accessory', 'Accessory')], default='tshirt', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.collection')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DesignStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField(help_text='Tell the story behind this design - inspiration, meaning, creative process')),
                ('author', models.CharField(default='HENDOSHI Design Team', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_story', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Design Stories',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('2xl', '2XL'), ('3xl', '3XL'), ('4xl', '4XL'), ('5xl', '5XL')], max_length=10)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('charcoal', 'Charcoal Grey'), ('navy', 'Navy Blue'), ('red', 'Red')], max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Variants',
                'ordering': ['size', 'color'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
