# Generated by Django 5.2.10 on 2026-01-17 01:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Design Stories'},
        ),
        migrations.AddField(
            model_name='designstory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='designstory',
            name='author',
            field=models.CharField(blank=True, default='HENDOSHI Design Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='designstory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_stories', to='products.product'),
        ),
        migrations.AlterField(
            model_name='designstory',
            name='story',
            field=ckeditor.fields.RichTextField(help_text='Max 500 characters.', max_length=500),
        ),
        migrations.AlterField(
            model_name='designstory',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
