# Generated by Django 5.2.10 on 2026-01-17 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_designstory_options_designstory_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designstory',
            options={'verbose_name_plural': 'Design Stories'},
        ),
        migrations.AlterField(
            model_name='designstory',
            name='author',
            field=models.CharField(default='HENDOSHI Design Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='designstory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_story', to='products.product'),
        ),
        migrations.AlterField(
            model_name='designstory',
            name='story',
            field=models.TextField(help_text='Tell the story behind this design - inspiration, meaning, creative process. Max 500 characters.', max_length=500),
        ),
        migrations.AlterField(
            model_name='designstory',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='BattleVest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_vest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Battle Vest',
                'verbose_name_plural': 'Battle Vests',
            },
        ),
        migrations.CreateModel(
            name='BattleVestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('battle_vest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.battlevest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_vest_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Battle Vest Item',
                'verbose_name_plural': 'Battle Vest Items',
                'ordering': ['-added_at'],
                'unique_together': {('battle_vest', 'product')},
            },
        ),
    ]
