# Generated by Django 6.0.1 on 2026-01-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_end',
            field=models.DateTimeField(blank=True, help_text='When the sale ends (optional)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price. Leave blank if not on sale.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start',
            field=models.DateTimeField(blank=True, help_text='When the sale starts (optional)', null=True),
        ),
    ]
