# Generated by Django 5.2.10 on 2026-01-27 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_product_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Public reply from store admin'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='admin_reply_at',
            field=models.DateTimeField(blank=True, help_text='When the admin reply was posted', null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='admin_reply_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who replied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productreview')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
                'ordering': ['order'],
            },
        ),
    ]
