# Generated by Django 5.2.10 on 2026-01-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_review_images_and_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='requires_color',
            field=models.BooleanField(default=True, help_text='If checked, products of this type require a color selection before adding to cart.'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='requires_size',
            field=models.BooleanField(default=True, help_text='If checked, products of this type require a size selection before adding to cart.'),
        ),
    ]
