# Generated by Django 5.2.10 on 2026-01-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_variant_requirements_to_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('', '---------'), ('n/a', 'N/A'), ('black', 'Black'), ('white', 'White'), ('charcoal', 'Charcoal Grey'), ('navy', 'Navy Blue'), ('red', 'Red')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('', '---------'), ('one_size', 'One Size'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('2xl', '2XL'), ('3xl', '3XL'), ('4xl', '4XL'), ('5xl', '5XL')], default='', max_length=10),
        ),
    ]
