# Generated by Django 5.2.10 on 2026-02-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('accessory', 'Accessory'), ('custom', 'Custom')], default='custom', help_text='Category grouping for bulk creation and filtering.', max_length=20),
        ),
        migrations.AddField(
            model_name='producttype',
            name='default_stock',
            field=models.IntegerField(default=500, help_text='Default stock quantity for variants when creating products of this type in bulk.'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='requires_audience',
            field=models.BooleanField(default=True, help_text='If checked, products of this type require an audience selection (Men/Women/Kids/Unisex).'),
        ),
    ]
